### ISSUE TITLE
Please tag a version

### ISSUE THREAD

**Issue by SvenRtbg** [johnkary/phpunit-speedtrap#14]
Using a branch (even aliased with 1.0) leads to cloning this repository instead of downloading a version.
Tagging the current state will allow people to make use of this work easier. If you fear you are not ready yet, use an alpha tag like "1.0.0-alpha.1". This would even allow incompatible changes according to semver.org:

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

**Comment by afterdesign** [comment]
:+1: on this

**Comment by johnkary** [comment]
v1.0.1 is now tagged. Enjoy!
