### ISSUE TITLE
Use speedtrap as printer

### ISSUE THREAD

**Issue by Neppord** [johnkary/phpunit-speedtrap#16]
Hey, this is more of a question then a issue, sorry.

I'm trying to configure speedtrap from the command line instead of from the config file.

Mainly since I want it to be a option per run not per every run.

this option doesen't seam to work.

```
--printer <printer>       TestListener implementation to use.
```

```
Could not use "JohnKary\PHPUnit\Listener\SpeedTrapListener" as printer.
```

**Comment by REBELinBLUE** [comment]
I don't think the `--printer` option does that, that is the equivalent of the `printerClass` attribute on the root tag in the XML

**Comment by keradus** [comment]
no, this shall not be done as a printer.
printer would require us to actually print whole printout, like inherit it from one of the printers, but that would kill other printer formats.
as a listener, user might print in any format, and still get speedtrap executed.

IMO, this one shall be closed.

**Comment by johnkary** [comment]
@keradus @REBELinBLUE Thank you for your input!

@Neppord If you discover any way to code this type of feature please open a PR. Based on feedback above we will close this issue.
