### ISSUE TITLE
Missing maintainer?

### ISSUE THREAD

**Issue by TomasVotruba** [johnkary/phpunit-speedtrap#22]
Has this package some attention? Seems like abandoned, which is pity.

**Comment by JoolsMcFly** [comment]
Last activity was june last year... Are you concerned about phpunit 6?

**Comment by johnkary** [comment]
This project is not abandoned. This listener is stable, very small and focused, and nearly feature-complete. It doesn't require much new development aside from version bumps or small API changes for major PHPUnit versions. There's a difference between the two.

@TomasVotruba I see your new comments on the issues yesterday. Thank you for helping respond to issues.

@JoolsMcFly PHPUnit 6 just went stable a few days ago. I'm not using 6 in any projects yet. If you are, and see how we can update the library, I'll gladly accept PRs.

If there are issues or features you feel strongly about please +1 their original post or open new feature requests.

**Comment by TomasVotruba** [comment]
I can't see you're maintainer. 
That's why I opened this issue.

Alright then.

I use PHPUnit everywhere now, since I also use PHP 7.1.
