### ISSUE TITLE
Title "You should really fix these slow tests (>500ms)..." does not take the value from config.

### ISSUE THREAD

**Issue by briedis** [johnkary/phpunit-speedtrap#28]
I've set a custom slow threshold, but this title seems to use a hardcoded value.

**Comment by erunion** [comment]
Can you paste your config?

**Comment by briedis** [comment]
https://gist.github.com/briedis/47f5e18ee2e5687c9592c448aafa11b0

**Comment by briedis** [comment]
Ah, sorry, I found the problem. Arguments were not in the right tag.
