### ISSUE TITLE
PHPUnit 6.0.10 not working with 1.0.2

### ISSUE THREAD

**Issue by redaxmedia** [johnkary/phpunit-speedtrap#32]
Hello,

I guess that 1.0.2 was a patch release to support PHPUnit 6.x so I tried it while migrating.

However, it throws an fatal error:

> PHP Fatal error:  Interface 'PHPUnit_Framework_TestListener' not found in /home/.../redaxscript/vendor/johnkary/phpunit-speedtrap/src/JohnKary/PHPUnit/Listener/SpeedTrapListener.php on line 9
> Warning: Command failed: vendor/bin/phpunit --configuration=phpunit.xml

After that I used "dev-master" for speedtrap and the testing suite worked again.

> Updating dependencies (including require-dev)
>   - Updating johnkary/phpunit-speedtrap (v1.0.2 => dev-master cbd785f)
>     Checking out cbd785f67116c581f71705342cb316631e5a2be9

**Comment by redaxmedia** [comment]
1.0.2: https://github.com/johnkary/phpunit-speedtrap/blob/master/src/SpeedTrapListener.php
master: https://github.com/johnkary/phpunit-speedtrap/blob/v1.0.2/src/JohnKary/PHPUnit/Listener/SpeedTrapListener.php

Looks like this issue has been solved - could you please create a tag?

**Comment by johnkary** [comment]
@redaxmedia I have published tag `v1.0.3` that properly limits PHPUnit support to <6.0.

Could you try updating and let me know how it works for you?

**Comment by redaxmedia** [comment]
I tried 1.0.3 and 1.1.0 and it returned

```
  Problem 1
    - Installation request for johnkary/phpunit-speedtrap 1.1.0 -> satisfiable by johnkary/phpunit-speedtrap[v1.1.0].
    - johnkary/phpunit-speedtrap v1.1.0 requires phpunit/phpunit >=4.7,<6.0 -> satisfiable by phpunit/phpunit[4.7.0, 4.7.1, 4.7.2, 4.7.3, 4.7.4, 4.7.5, 4.7.6, 4.7.7, 4.7.x-dev, 4.8.0, 4.8.1, 4.8.10, 4.8.11, 4.8.12, 4.8.13, 4.8.14, 4.8.15, 4.8.16, 4.8.17, 4.8.18, 4.8.19, 4.8.2, 4.8.20, 4.8.21, 4.8.22, 4.8.23, 4.8.24, 4.8.25, 4.8.26, 4.8.27, 4.8.28, 4.8.29, 4.8.3, 4.8.30, 4.8.31, 4.8.32, 4.8.33, 4.8.34, 4.8.35, 4.8.4, 4.8.5, 4.8.6, 4.8.7, 4.8.8, 4.8.9, 4.8.x-dev, 5.0.0, 5.0.1, 5.0.10, 5.0.2, 5.0.3, 5.0.4, 5.0.5, 5.0.6, 5.0.7, 5.0.8, 5.0.9, 5.0.x-dev, 5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.1.4, 5.1.5, 5.1.6, 5.1.7, 5.1.x-dev, 5.2.0, 5.2.1, 5.2.10, 5.2.11, 5.2.12, 5.2.2, 5.2.3, 5.2.4, 5.2.5, 5.2.6, 5.2.7, 5.2.8, 5.2.9, 5.2.x-dev, 5.3.0, 5.3.1, 5.3.2, 5.3.3, 5.3.4, 5.3.5, 5.3.x-dev, 5.4.0, 5.4.1, 5.4.2, 5.4.3, 5.4.4, 5.4.5, 5.4.6, 5.4.7, 5.4.8, 5.4.x-dev, 5.5.0, 5.5.1, 5.5.2, 5.5.3, 5.5.4, 5.5.5, 5.5.6, 5.5.7, 5.5.x-dev, 5.6.0, 5.6.1, 5.6.2, 5.6.3, 5.6.4, 5.6.5, 5.6.6, 5.6.7, 5.6.8, 5.6.x-dev, 5.7.0, 5.7.1, 5.7.10, 5.7.11, 5.7.12, 5.7.13, 5.7.14, 5.7.15, 5.7.16, 5.7.17, 5.7.2, 5.7.3, 5.7.4, 5.7.5, 5.7.6, 5.7.7, 5.7.8, 5.7.9, 5.7.x-dev] but these conflict with your requirements or minimum-stability.

Using **"phpunit/phpunit": "6.0.10"** in my composer.json.
```

**Comment by johnkary** [comment]
@redaxmedia To use PHPUnit 6 you'll need to require phpunit-speedtrap `dev-master` or `2.0.x-dev`. I want to implement these two features before tagging 2.0 because they will break backwards compatibility with the listener:

* #27 Enable/Disable listener per-test suite
* #29 Report should display exceeded slowness threshold for each test

The newly tagged v1.0.3 and v1.1 solve the original issue in this ticket #32 by setting upper-bounds on the compatible PHPUnit version. Composer will no longer allow installing PHPUnit 6 alongside phpunit-speedtrap 1.0.3 or 1.1.

**Comment by redaxmedia** [comment]
Well, I asked for a version to use PHPUnit 6 ... so no idea what you did here :D

**Comment by johnkary** [comment]
@redaxmedia There is a `2.0.x-dev` version. See here: https://packagist.org/packages/johnkary/phpunit-speedtrap#dev-master

No future version of 1.0 and 1.1 will support PHPUnit 6.

Since the latest 1.0.3 now prevents installing PHPUnit 6 this ticket can be closed.

**Comment by redaxmedia** [comment]
Please tag a 2.0.0-beta release then - I dislike the idea to use dev-master...

**Comment by johnkary** [comment]
@redaxmedia v2.0.0-BETA1 is now tagged :)

**Comment by redaxmedia** [comment]
Great move!

Works for me... thank you
