### ISSUE TITLE
Support for PHPUnit 6 and up

### ISSUE THREAD

**Issue by stemis** [johnkary/phpunit-speedtrap#34]
Hello,

I would like to have this running on PHPUnit 6.0.8, is it possible to add support for that?

Regards
Steff

**Comment by johnkary** [comment]
@stemis Hi Steff. Version 2.0.0-BETA1 supports PHPUnit 6 with PHP 7. Try requiring the beta version:

    $ composer require --dev johnkary/phpunit-speedtrap v2.0.0-BETA1
