### ISSUE TITLE
Tag version for PHPUnit 6.0

### ISSUE THREAD

**Issue by TomasVotruba** [johnkary/phpunit-speedtrap#35]
Please, could you tag version for PHPUnit 6.0? It's not supported now :( 

![image](https://cloud.githubusercontent.com/assets/924196/25499553/1e4bad3e-2b8c-11e7-82fb-080359c77950.png)

**Comment by b1rdex** [comment]
`composer require --dev johnkary/phpunit-speedtrap v2.0.0-BETA1`

**Comment by TomasVotruba** [comment]
I used that, sure

**Comment by TomasVotruba** [comment]
Outdated
