### ISSUE TITLE
Can you add support for PHPUnit > 6?

### ISSUE THREAD

**Issue by Cayan** [johnkary/phpunit-speedtrap#37]
I was trying to install this extension into my project, but I stumbled into this problem

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Conclusion: don't install phpunit/phpunit 6.3.0
>     - johnkary/phpunit-speedtrap 1.1.x-dev requires phpunit/phpunit >=4.7,<6.0 -> satisfiable by phpunit/phpunit[4.7.x-dev, 4.8.x-dev, 5.0.x-dev, 5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev].
>     - johnkary/phpunit-speedtrap v1.1.0 requires phpunit/phpunit >=4.7,<6.0 -> satisfiable by phpunit/phpunit[4.7.x-dev, 4.8.x-dev, 5.0.x-dev, 5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev].
>     - Can only install one of: phpunit/phpunit[4.8.x-dev, 6.3.0].
>     - Can only install one of: phpunit/phpunit[5.6.x-dev, 6.3.0].
>     - Can only install one of: phpunit/phpunit[5.7.x-dev, 6.3.0].
>     - Can only install one of: phpunit/phpunit[4.7.x-dev, 6.3.0].
>     - Can only install one of: phpunit/phpunit[5.0.x-dev, 6.3.0].
>     - Can only install one of: phpunit/phpunit[5.1.x-dev, 6.3.0].
>     - Can only install one of: phpunit/phpunit[5.2.x-dev, 6.3.0].
>     - Can only install one of: phpunit/phpunit[5.3.x-dev, 6.3.0].
>     - Can only install one of: phpunit/phpunit[5.4.x-dev, 6.3.0].
>     - Can only install one of: phpunit/phpunit[5.5.x-dev, 6.3.0].
>     - Installation request for phpunit/phpunit (locked at 6.3.0, required as ~6.1) -> satisfiable by phpunit/phpunit[6.3.0].
>     - Installation request for johnkary/phpunit-speedtrap ^1.1 -> satisfiable by johnkary/phpunit-speedtrap[1.1.x-dev, v1.1.0].

**Comment by marcelopm** [comment]
:+1:

**Comment by johnkary** [comment]
Hi @Cayan, You can install phpunit-speedtrap for PHPUnit 6.0+ using v2.0.0-BETA1:

    $ composer require --dev johnkary/phpunit-speedtrap v2.0.0-BETA1

Please close this issue if that works for you. I hope to have 2.0 ready soon.

**Comment by Cayan** [comment]
It worked perfectly!
