### ISSUE TITLE
johnkary/phpunit-speedtrap v1.1.0 requires phpunit/phpunit >=4.7,<6.0

### ISSUE THREAD

**Issue by solofeed** [johnkary/phpunit-speedtrap#38]
Could you please update package for compatible with phpunit 6.4

**Comment by johnkary** [comment]
Hi @solofeed, v2.0.0 has been tagged as of this morning, December 6, 2017. Version 2.0 requires minimum versions of PHPUnit 6.0+ and PHP 7.0+.

You can update to the latest version by running:

    $ composer require johnkary/phpunit-speedtrap ^2.0

If you experience any other issues please let me know :)

**Comment by solofeed** [comment]
@johnkary Thank you :+1:
