### ISSUE TITLE
Request: please tag v2.0.0 final

### ISSUE THREAD

**Issue by luispabon** [johnkary/phpunit-speedtrap#40]
I've been using speedtrap v2.0.0-BETA1 on php 7.2 and phpunit 6.5 for a while now, with zero problems. I reckon this is good to go as-is.

It's the only non-stable dependency I have around my projects at the moment.

**Comment by johnkary** [comment]
Hi @luispabon, `v2.0.0` has been tagged as of this morning, December 6, 2017.

If you experience any other issues please let me know :)

**Comment by luispabon** [comment]
Will do, thank you :+1:
