### ISSUE TITLE
Support PHPUnit 7.0

### ISSUE THREAD

**Issue by Avariya** [johnkary/phpunit-speedtrap#42]
PHPUnit 7.0 was released
Releases notes: https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-7.0.md

Would be nice to see new major version support at phpunit-speedtrap. Looks like it will be not hard to add.

**Comment by Trainmaster** [comment]
There is already an open MR: https://github.com/johnkary/phpunit-speedtrap/pull/41

**Comment by Avariya** [comment]
Let's merge it so. Sorry :)
