### ISSUE TITLE
Add Travis CI build against PHPUnit dev-master

### ISSUE THREAD

**Issue by johnkary** [johnkary/phpunit-speedtrap#44]
phpunit-speedtrap depends on PHPUnit features that sometimes change when new versions are released. Currently phpunit-speedtrap maintainers manually check for compatibility when official PHPUnit versions are released (or when helpful users report issues on GitHub :) )

Is it possible to add a [canary build](https://www.thoughtworks.com/radar/techniques/canary-builds) for phpunit-speedtrap Travis CI build matrix that tests against the latest PHPUnit dev-master on a nightly or weekly schedule? The build should be allowed to fail.

Sebastian Bergmann and all PHPUnit contributors do an amazing job maintaining PHPUnit by frequently releasing new versions to fix bugs, add new minor features and occasionally introduce backwards-incompatible features.

Due to PHPUnit's rapid release pace, a canary build would more quickly indicate BC breaks in phpunit-speedtrap, allowing maintainers to more quickly update the library before new major PHPUnit versions are available.

**Comment by keradus** [comment]
To test against dev-master a travis config file has to be changed, one of possible ways: #45

to make a schedule checks, it's possible, it's up to Travis global configuration - go to Travis settings page, then you will find cron settings: https://docs.travis-ci.com/user/cron-jobs/

**Comment by johnkary** [comment]
Weekly cron builds have been setup in Travis CI using PHP nightly and PHPUnit dev-master: https://travis-ci.org/johnkary/phpunit-speedtrap/builds

@keradus Thank you for your PR and Travis docs to get this setup!

**Comment by keradus** [comment]
looks great !
