### ISSUE TITLE
Display @dataProvider parameters

### ISSUE THREAD

**Issue by lukepass** [johnkary/phpunit-speedtrap#61]
Hello, when using tests with parameters it could be useful to actually show the parameters' values.

```
You should really fix these slow tests (>50ms)...
 1. 309ms to run Tests\AppBundle\Admin\AdminTest:testAdminRoutes with data set #0
 2. 276ms to run Tests\AppBundle\Admin\AdminTest:testAdminRoutes with data set #57
 3. 165ms to run Tests\AppBundle\Admin\AdminTest:testAdminRoutes with data set #1
 4. 122ms to run Tests\AppBundle\Admin\AdminTest:testAdminRoutes with data set #34
 5. 121ms to run Tests\AppBundle\Admin\AdminTest:testAdminRoutes with data set #54
```

Thanks!

**Comment by johnkary** [comment]
@lukepass That's a great idea! If anyone can add this feature let's do it.

**Comment by willemstuursma** [comment]
Not necessary. You can set keys as names for the dataproviders that will also make it clearer which tests ran when using PHPUnit:

```
public function dpSomeDataForTests(): array {
    return [
        "condition 1" => ["param1", "param2"],
        "condition 2" => ["param1", "param3"],
    ];
}
```

**Comment by johnkary** [comment]
@lukepass As @willemstuursma showed above, if you add a string before each @dataProvider entry it will output in the slowness threshold report. The PHPUnit documentation has great examples here: https://phpunit.readthedocs.io/en/8.3/writing-tests-for-phpunit.html#writing-tests-for-phpunit-data-providers-examples-datatest1-php

Thanks for making this suggestion! 🚀
