### ISSUE TITLE
Compatibility with PHPUnit 9

### ISSUE THREAD

**Issue by NicoHaase** [johnkary/phpunit-speedtrap#69]
PHPUnit 9 is expected to be released in the next weeks. There's already a deprecation warning shown when running tests with PHPUnit 8.5:

> The "JohnKary\PHPUnit\Listener\SpeedTrapListener" class implements "PHPUnit\Framework\TestListener" that is deprecated Use the `TestHook` interfaces instead.

**Comment by johnkary** [comment]
Hi @NicoHaase, Thank you for reporting the deprecation message!

PHPUnit 9.0 compatibility is now supported with just released version 3.2.0 of johnkary/phpunit-speedtrap. This release uses the same implementation as previous versions, which means the deprecation notice will remain for v3.2.0.

We will soon release a new v4.0 that converts to using `TestHook`, which will remove the deprecation notice.
